function(add_warning_target target)
	if(ENABLE_WARNING)
		if(MSVC)
			target_compile_options(${target} PRIVATE /W4 /permissive-)
		else()
			target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
		endif()
	endif()
endfunction()